training_route:
  map: "small_warehouse"
  launch_file_location: "/home/xanial/ros/noetic/repos/github.com/CardiffUniversityComputationalRobotics/social-robot-nav-tests/pepper_social_nav_tests/launch/smf_nav_stack_test.launch"
  num_waypoints: 3
  max_route_time: 120
  starting_position: [[0.9, 7.09],
    [-3.32, 8.55],
    [-3.47, -8.69],
    [1.47, -8.55],
    [6.0, 2.09]]

record_maps:
  folder_path: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/small_warehouse/raw_maps/without_coords"
  ogm_topic: "/grid_map_visualization/obstacles"
  sgm_topic: "/smf_move_base_mapper/social_grid_map"
  max_files: 30

record_maps_coords:
  folder_path: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/small_warehouse/raw_maps/with_coords"
  ogm_topic: "/grid_map_visualization/obstacles"
  sgm_topic: "/smf_move_base_mapper/social_grid_map"
  odom_topic: "/pepper/odom_groundtruth"
  max_files: 30

split_maps:
  directory_path_input: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/raw_maps/without_coords"
  directory_path_output: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/split_maps/without_coords"

create_SDHM:
  folderPathInput: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/split_maps/without_coords"
  folderPathOutput: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/final_maps/without_coords"

create_SDHM_coords:
  folderPathInput: "/home/danielhixson/socNavProject/ml_ros_package/ml_pipeline_package/data/office/eval/without_coords/split_maps"
  folderPathOutput: "/home/danielhixson/socNavProject/ml_ros_package/ml_pipeline_package/data/office/eval/without_coords/cropped_maps"

FCN:
  file_path_input: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/final_maps/without_coords"
  file_path_output: "ml_pipeline_package/data/trained_models/bookstore/"
  lower_bound_threshold: 0.1
  upper_bound_threshold: 0.5
  weighted: false
  class_matrix: [[3860989,  524777,  323086],[ 377772,  148099,   53876],[  99907,   36103,   31263]]
  training_image_size: [128,128]
  batch_size: 64
  num_epochs: 50
  model_name: "weirdloss64batch"

CNN:
  file_path_input: "ml_pipeline_package/data/maps_with_coords/maps_SDHM_cropped/office"
  file_path_output: "ml_pipeline_package/data/trained_models/office"
  lower_bound_threshold: 0.1
  upper_bound_threshold: 0.5
  weighted: 
  class_matrix: [[3860989,  524777,  323086],
        [ 377772,  148099,   53876],
        [  99907,   36103,   31263]]
  training_image_size: [128,128]
  batch_size: 6
  num_epochs: 2
  model_name: "CNN"

eval_FCN:
  model_location: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/trained_models/bookstore/weirdloss64batchFCN.pt"
  eval_data_location: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/eval/without_coords/final_maps"
  training_image_size: [128,128]
  batch_size: 64
  lower_bound_threshold: 0.1
  upper_bound_threshold: 0.5

eval_CNN:
  model_location: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/trained_models/bookstore/noweights.pt"
  eval_data_location: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/final_maps/without_coords"
  training_image_size: [128,128]
  batch_size: 4
  lower_bound_threshold: 0.1
  upper_bound_threshold: 0.5




