training_route:
  map: "small_warehouse"
  num_waypoints: 3
  waypoint_topic: "/pedsim_visualizer/waypoints"
  goal_result_topic: "/smf_goto_action/result"
  max_route_time: 120
  starting_position: [[0.9, 7.09],
    [-3.32, 8.55],
    [-3.47, -8.69],
    [1.47, -8.55],
    [6.0, 2.09]]

record_maps:
  folder_path: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/small_warehouse/raw_maps/without_coords"
  ogm_topic: "/grid_map_visualization/obstacles"
  sgm_topic: "/smf_move_base_mapper/social_grid_map"
  max_files: 30

record_maps_coords:
  folder_path: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/small_warehouse/raw_maps/with_coords"
  ogm_topic: "/grid_map_visualization/obstacles"
  sgm_topic: "/smf_move_base_mapper/social_grid_map"
  odom_topic: "/pepper/odom_groundtruth"
  max_files: 30

split_maps:
  directory_path_input: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/raw_maps/without_coords"
  directory_path_output: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/split_maps/without_coords"

create_SDHM:
  folderPathInput: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/split_maps/without_coords"
  folderPathOutput: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/final_maps/without_coords"

create_SDHM_coords:
  folderPathInput: "/home/danielhixson/socNavProject/ml_ros_package/ml_pipeline_package/data/office/eval/without_coords/split_maps"
  folderPathOutput: "/home/danielhixson/socNavProject/ml_ros_package/ml_pipeline_package/data/office/eval/without_coords/cropped_maps"

FCNv1:
  file_path_input: "ml_pipeline_package/data/maps_without_coords/maps_SDHM_cropped/office"
  file_path_output: "ml_pipeline_package/data/trained_models/office"
  training_image_size: [128,128]
  criterion: 1
  optimiser: 2
  num_classes: 3
  batch_size: 6
  num_epochs: 50
  dict: 1
  lower_bound_threshold: 100
  upper_bound_threshold: 700
  learning_rate: 0.001
  momentum: 0.9
  betas: [0.9, 0.999]
  alpha: 0.9
  rho: 0.9

FCNv2:
  file_path_input: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/final_maps/without_coords"
  file_path_output: "ml_pipeline_package/data/trained_models/bookstore/"
  training_image_size: [128,128]
  criterion: 1
  optimiser: 2
  num_classes: 3
  batch_size: 32
  num_epochs: 50
  dict: 1
  lower_bound_threshold: 100
  upper_bound_threshold: 700
  learning_rate: 0.001
  momentum: 0.9
  betas: [0.9, 0.999]
  alpha: 0.9
  rho: 0.9

CNNv1:
  file_path_input: "ml_pipeline_package/data/maps_with_coords/maps_SDHM_cropped/office"
  file_path_output: "ml_pipeline_package/data/trained_models"
  training_image_size: [128,128]
  criterion: 1
  optimiser: 3
  num_classes: 3
  batch_size: 12
  num_epochs: 2
  dict: 1
  lower_bound_threshold: 100
  upper_bound_threshold: 700
  learning_rate: 0.001
  momentum: 0.9
  betas: [0.9, 0.999]
  alpha: 0.9
  rho: 0.9

CNNv2:
  file_path_input: "ml_pipeline_package/data/maps_with_coords/maps_SDHM_cropped/office"
  file_path_output: "ml_pipeline_package/data/trained_models/office"
  training_image_size: [128,128]
  criterion: 1
  optimiser: 3
  num_classes: 3
  batch_size: 12
  num_epochs: 2
  dict: 1
  lower_bound_threshold: 100
  upper_bound_threshold: 700
  learning_rate: 0.001
  momentum: 0.9
  betas: [0.9, 0.999]
  alpha: 0.9
  rho: 0.9



