training_route:
  map: "small_warehouse"
  launch_file_location: "/home/xanial/ros/noetic/repos/github.com/CardiffUniversityComputationalRobotics/social-robot-nav-tests/pepper_social_nav_tests/launch/smf_nav_stack_test.launch"
  num_waypoints: 3
  max_route_time: 120
  starting_position: [[0.9, 7.09],
    [-3.32, 8.55],
    [-3.47, -8.69],
    [1.47, -8.55],
    [6.0, 2.09]]

record_maps:
  folder_path: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/"
  max_files: 30

record_maps_coords:
  folder_path: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/small_warehouse/raw_maps/with_coords"
  max_files: 30

split_maps:
  directory_path_input: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/raw_maps/with_coords"
  directory_path_output: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/split_maps/with_coords"

create_SDHM:
  folderPathInput: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/split_maps/without_coords"
  folderPathOutput: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/final_maps/without_coords"

create_SDHM_coords:
  folder_path_input: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/eval/with_coords/split_maps"
  folder_path_output: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/eval/with_coords/final_maps"

FCN:
  file_path_input: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/final_maps/without_coords"
  file_path_output: "ml_pipeline_package/data/trained_models/bookstore/"
  weighted: False
  class_matrix: [[5065466,   67730,   14963],
        [ 206475,   13469,    2245],
        [  72070,    7748,    5706]]
  training_image_size: [128,128]
  batch_size: 64
  num_epochs: 100
  model_name: "100epochs_64batch_Unweighted_Bookstore"

CNN:
  file_path_input: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/final_maps/with_coords"
  file_path_output: "ml_pipeline_package/data/trained_models/bookstore"
  weighted: False
  class_matrix: [[5019663,  106704,   21792],
        [ 201025,   17706,    3458],
        [  69430,    8066,    8028]]
  training_image_size: [128,128]
  batch_size: 64
  num_epochs: 100
  model_name: "100epochs_64batch_Unweighted_Bookstore"

eval_FCN:
  model_location: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/trained_models/bookstore/100epochs_64batch_Unweighted_Bookstore_FCN.pt"
  eval_data_location: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/eval/without_coords/final_maps"
  training_image_size: [128,128]
  batch_size: 16

eval_CNN:
  model_location: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/trained_models/bookstore100epochs_64batch_Unweighted_Bookstore_CNN.pt"
  eval_data_location: "/home/xanial/FINAL_YEAR_PROJECT/ml_ros_package/ml_pipeline_package/data/bookstore/eval/with_coords/final_maps"
  training_image_size: [128,128]
  batch_size: 64




